apiVersion: v1
kind: Pod
metadata:
  name: helloworld  
  labels:
    name: Test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
