version: '2'

name: 'universal'

services:
  webserver:
    image: nginx:latest
    networks: 
      - universal_network
    ports:
      - 80:80
  
  dind:
    image: docker:dind
    networks:
      - universal_network
    ports:
      - 2376:2376
    volumes:
      - dind_certs:/certs
      - jenkins_certs:/certs/client
      - jenkins_data:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    command: --storage-driver=overlay2

  monitoring:
    image: prom/prometheus:latest
    networks:
      - universal_network
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana-enterprise:latest
    networks:
      - universal_network
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana

networks:
  universal_network:

volumes:
  grafana_storage: {}
  dind_certs: {}
  jenkins_certs: {}
  jenkins_data: {}