version: '2'

name: 'universal'

services:
  webserver:
    image: nginx:latest
    networks: 
      - universal_network
    ports:
      - 80:80

  monitoring:
    image: prom/prometheus:latest
    networks:
      - universal_network
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana-enterprise:latest
    networks:
      - universal_network
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana

networks:
  universal_network:

volumes:
  grafana_storage: {}