// Simple declarative pipeline
pipeline {
    agent none
    stages {
        stage('Build') {
            agent any
            steps {
                sh 'ls -lsa'
                sh 'docker version'
            }
        }
    }
}
