// Simple declarative pipeline
pipeline {
    agent none
    tools {
        maven 'maven'
    }
    stages {
        stage('Build') {
            agent  {
                label 'agent'
            }
            steps {
                sh 'ls -lsa'
                sh 'mvn --version'
            }
        }
    }
}
